POST http://localhost:4000/ads
Content-Type: application/json

{
  "title": "Vélo",
  "description": "lorem ipsum",
  "owner": "a@a.com",
  "price": 500,
  "picture": "",
  "location": "Paris",
  "category": 3,
  "tags": [1, 2]
}